// Public surface of @tupiflow-plugins/shared. Re-exported one symbol at a
// time so the bundle stays tree-shakeable and tupiflow's "no barrel files"
// rule isn't violated by a wildcard re-export. Consumers should prefer
// the subpath exports (e.g. "@tupiflow-plugins/shared/build-helpers") and
// only use this entrypoint when they really need a single import line.

export {
  ALLOWED_NPM_DEPS,
  BLESSED_HOST_MODULES,
  buildPlugin,
} from "./build-helpers.ts";
export type {
  BuildPluginOptions,
  BuildPluginResult,
  WorkerBuildOutput,
} from "./build-helpers.ts";

export {
  MissingNpmDepError,
  NpmDepNotAllowedError,
  WorkerCapabilityDeniedError,
  WorkerNotFoundError,
  WorkerTimeoutError,
} from "./host-api-types.ts";
export type {
  Action,
  AgentCreateSpec,
  AgentListFilter,
  AgentListItem,
  AgentUpdatePatch,
  ChatAttachment,
  ChatMessageEvent,
  ConnectionInstance,
  ConnectionSendReplyResult,
  ConnectionSendReplySpec,
  ConnectionSpec,
  CreateExecutionSpec,
  CreateExecutionResult,
  DbCallOpts,
  EmbedArgs,
  EmbedResult,
  ErrorNotificationFailedNode,
  ErrorNotificationResult,
  ErrorNotificationSpec,
  ExecutionLogEntry,
  HttpMethod,
  IntegrationConfigPatch,
  IntegrationListFilter,
  IntegrationListItem,
  IntegrationRegistrationSpec,
  IntegrationSpec,
  LaunchAgentOpts,
  LaunchAgentResult,
  LlmCallArgs,
  LlmCallResult,
  PluginDb,
  PluginHostAPI,
  PluginLogger,
  RegistryStepContext,
  RegistryStepHandler,
  RegistryStepInput,
  RouteContext,
  RouteHandler,
  RouteRequest,
  SandboxErrorKind,
  SandboxFailure,
  SandboxOpts,
  SandboxResult,
  SandboxSuccess,
  StepHandler,
  StepResult,
  TakeoverTargetSpec,
  TestHandler,
  TestIntegrationResult,
  TestIntegrationSpec,
  Tool,
  ToolCatalogContext,
  ToolCatalogContributor,
  ToolCatalogEntry,
  ToolHandler,
  Workflow,
  WorkerSpec,
  WorkflowCreateSpec,
  WorkflowEdge,
  WorkflowExecution,
  WorkflowListItem,
  WorkflowListOpts,
  WorkflowListPage,
  WorkflowNode,
} from "./host-api-types.ts";

export { assertPublicHost, assertPublicUrl } from "./ssrf.ts";

export type {
  Manifest,
  ManifestAction,
  ManifestActionTool,
  ManifestBundle,
  ManifestConnection,
  ManifestCredential,
  ManifestFormField,
  ManifestIcon,
  ManifestIconLucide,
  ManifestIconSvg,
  ManifestIdentity,
  ManifestRequiredExtension,
  ManifestRoute,
  ManifestRuntime,
  ManifestSchemaBlock,
  ManifestTakeoverTarget,
} from "./manifest-types.ts";
